# Generated by Django 3.1.3 on 2021-04-28 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 4, 28, 15, 10, 3, 443340, tzinfo=utc), verbose_name='datetime')),
                ('parent_region', models.CharField(max_length=150, verbose_name='parent_region')),
                ('region', models.CharField(max_length=150, verbose_name='region')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='region')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('long', models.FloatField(verbose_name='longitude')),
                ('category', models.CharField(blank=True, max_length=150, null=True, verbose_name='category')),
                ('light', models.CharField(blank=True, max_length=150, null=True, verbose_name='light')),
            ],
        ),
    ]
