# Generated by Django 3.1.3 on 2021-04-28 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0002_auto_20210428_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='loc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='org',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='per',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
